CREATE TABLE users (
  username VARCHAR(25) PRIMARY KEY,
  password TEXT NOT NULL
);

CREATE TABLE images (
  id SERIAL PRIMARY KEY,
  s3_url TEXT NOT NULL,
  creator VARCHAR(25) NOT NULL REFERENCES users ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);