CREATE TABLE users (
  username VARCHAR(25) PRIMARY KEY,
  password TEXT NOT NULL
);

CREATE TABLE albums (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  is_private BOOLEAN NOT NULL DEFAULT false,
  creator VARCHAR(25) NOT NULL REFERENCES users ON DELETE CASCADE
);

CREATE TABLE images (
  id SERIAL PRIMARY KEY,
  s3_url TEXT NOT NULL,
  is_private BOOLEAN NOT NULL DEFAULT false,
  creator VARCHAR(25) NOT NULL REFERENCES users ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE images_albums (
  image_id SERIAL NOT NULL REFERENCES images ON DELETE CASCADE,
  album_id SERIAL NOT NULL REFERENCES albums ON DELETE CASCADE
)

